"""
Simple smoke test for the MVP agents.

This script:
- reads `test_payload.json` (generated by `get_test_ids.py`),
- calls each agent's `.run()` method directly (no HTTP server),
- sets `OMNICARE_DISABLE_LLM=1` to avoid calling Gemini during smoke tests.
"""

import json
import os
import sys
from datetime import date


def main():
    # Ensure deterministic/safe execution.
    os.environ["OMNICARE_DISABLE_LLM"] = "1"

    # Add parent dir to path so we can import from app.
    repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    sys.path.append(repo_root)

    from app.database import SessionLocal
    from app.models import Encounter

    from app.agents.ambient_scribe.agent import AmbientScribeAgent
    from app.agents.ambient_scribe.schemas import AmbientScribeRequest
    from app.agents.cds.agent import CDSAgent
    from app.agents.cds.schemas import CDSRequest
    from app.agents.follow_up.agent import FollowUpCarePlanAgent
    from app.agents.follow_up.schemas import FollowUpCarePlanRequest, MedicationOnDischarge
    from app.agents.care_coord.agent import CareCoordinationAgent
    from app.agents.care_coord.schemas import CareCoordRequest
    from app.agents.triage.agent import TriageAgent
    from app.agents.triage.schemas import MedicationAdherenceItem, TriageRequest, TriageSubmission
    from app.agents.post_discharge_rag.agent import PostDischargeRagAgent
    from app.agents.post_discharge_rag.schemas import RagChatRequest

    payload_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "test_payload.json")
    payload_path = os.path.normpath(payload_path)

    if not os.path.exists(payload_path):
        print(f"Missing {payload_path}. Run get_test_ids.py first.")
        return

    with open(payload_path, "r", encoding="utf-8") as f:
        payload = json.load(f)

    patient_id = payload.get("patient_id")
    encounter_id = payload.get("encounter_id")
    if not patient_id or not encounter_id:
        print("test_payload.json missing patient_id/encounter_id.")
        return

    db = SessionLocal()
    try:
        # Ambient Scribe + CDS
        print("Running Ambient Scribe...")
        ambient = AmbientScribeAgent()
        ascribe = ambient.run(
            db, AmbientScribeRequest(encounter_id=encounter_id, transcript_segments=None)
        )
        print("Ambient Scribe confidence:", ascribe.confidence_score)

        print("Running CDS...")
        cds = CDSAgent()
        cds_resp = cds.run(db, CDSRequest(encounter_id=encounter_id))
        print("CDS alerts count:", len(cds_resp.cds_alerts))

        # Follow-Up creates a CarePlan
        encounter = db.query(Encounter).filter(Encounter.id == encounter_id).first()
        if not encounter:
            raise RuntimeError(f"Encounter with ID {encounter_id} not found")
        provider_id = encounter.provider_id

        print("Running Follow-Up / Care Plan...")
        follow_up = FollowUpCarePlanAgent()
        follow_resp = follow_up.run(
            db,
            FollowUpCarePlanRequest(
                patient_id=patient_id,
                encounter_id=encounter_id,
                provider_id=provider_id,
                discharge_date=date.today(),
                discharge_summary="Discharged after procedure with wound/incision care instructions. Monitor for severe pain or bleeding.",
                medications_on_discharge=[
                    MedicationOnDischarge(
                        name="Metformin 500mg",
                        dosage="500mg",
                        frequency="BID",
                        route="PO",
                        duration="ongoing",
                    ),
                    MedicationOnDischarge(
                        name="Aspirin 75mg",
                        dosage="75mg",
                        frequency="Once daily",
                        route="PO",
                        duration="ongoing",
                    ),
                ],
            ),
        )
        print("Care plan created:", follow_resp.care_plan_id)

        # Care coordination
        print("Running Care Coordination...")
        care_coord = CareCoordinationAgent()
        coord_resp = care_coord.run(
            db,
            CareCoordRequest(
                care_plan_id=follow_resp.care_plan_id,
                preferred_pharmacy="MedPlus",
            ),
        )
        print("Coordination actions:", [a.action for a in coord_resp.actions_completed])

        # Triage on a simulated submission
        print("Running Triage...")
        triage = TriageAgent()
        triage_resp = triage.run(
            db,
            TriageRequest(
                care_plan_id=follow_resp.care_plan_id,
                submission=TriageSubmission(
                    submission_date=date.today(),
                    day_number=3,
                    pain_level=8,
                    temperature_f=100.6,
                    blood_pressure={"systolic": 150, "diastolic": 90},
                    mood="bad",
                    medication_adherence=[
                        MedicationAdherenceItem(
                            medication_name="Aspirin 75mg",
                            taken=False,
                        )
                    ],
                    free_text_notes="Severe pain near the incision site.",
                ),
            ),
        )
        print("Triage result:", triage_resp.triage_result)

        # Post-discharge RAG chatbot
        print("Running Post-Discharge RAG...")
        rag = PostDischargeRagAgent()
        rag_resp = rag.run(
            db,
            RagChatRequest(
                care_plan_id=follow_resp.care_plan_id,
                message="Can I drink alcohol with my Metformin?",
            ),
        )
        print("RAG confidence:", rag_resp.confidence_score)
    except Exception as e:
        print("Smoke test failed.")
        print("Reason:", str(e))
        print("Tip: ensure MySQL is running (docker-compose up) and that `services/ai-agents/.env` is present.")
    finally:
        db.close()


if __name__ == "__main__":
    main()

